### PR TITLE
Basic Email sending function in CE

### LINKED ISSUE #285: Basic Email sending function in CE
Hi,

is it possible to provide basic email sending function in CE ?

https://forum.openkm.com/viewtopic.php?f=5&t=24192

### PR DESCRIPTION
**Pull request by gnujavasergio**
Fix #285

### CODE REVIEW

**Comment by darkman97i** [comment]
@gnujavasergio Pending task:
* migration script to fill NML_ATTACHMENT ( with true or false )
```sql
<sql stage="post" dialect="generic" comment="Set mail has attachments">
    update OKM_NODE_MAIL set NML_ATTACHMENT='F';
    update OKM_NODE_MAIL set NML_ATTACHMENT='T' where NBS_UUID in (select * from (select NMD.NBS_UUID from OKM_NODE_BASE NBD, OKM_NODE_DOCUMENT ND, OKM_NODE_MAIL NMD where NBD.NBS_UUID=ND.NBS_UUID and NBD.NBS_PARENT=NMD.NBS_UUID) s);
  </sql>
```
* `index.jsp` using two tinymce at the same time ( because in the professional edition I think we have only a single tinymce set in this file -> maybe is required to change HTML editor to version 4 ) 
*  check import emails from email account

**Comment by gnujavasergio** [comment]
Correct import of emails  - **Import Check import emails from email account**
Selección_358

**Review by darkman97i — CHANGES_REQUESTED** [review]
The tinymce editor stop working. I think should be replac4e by tinymce4.

**Comment by gnujavasergio** [comment]
Hello @darkman97i,  the task is finished
This is needed because tinymce3 was removed
```sql
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.theme';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.skin';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.skin.variant';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.plugins';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.theme.buttons1';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.theme.buttons2';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.theme.buttons3';
DELETE FROM OKM_CONFIG WHERE CFG_KEY='tinymce.theme.buttons4';
```

**Comment by darkman97i** [comment]
@monkiki I have checked the application and specially the HTML editor.

**Review by darkman97i — DISMISSED** [review]

**Review by monkiki — APPROVED** [review]

**Pull request merged**
